### PR TITLE
Configurable label separator

### PR DESCRIPTION
**Pull request by pjagielski**
Added `:label-separator` option to allow omit `:`  between input label and input itself.

Also added basic tests for forms and fixed autocomplete tests.

### CODE REVIEW

**Comment by Deraen** [comment]
Some quick comments:
- `:label-separator` looks ok
- Use `cljs.test` instead of `cemerick.cljs.test`
- I will not accept adding third party code here if not necessary
  - React is available as jar from e.g. cljsjs
  - Es5-shim should be available from webjars

**Comment by pjagielski** [comment]
Ad `cljs.test` -> should I use a custom runner as in https://gitlab.com/keeds/cljsinit ?

**Comment by Deraen** [comment]
Ah, if cemerick.cljs.test still has some stuff which is not included with cljs.test, it's okay to use the former. I'm not sure if the library you linked does anything?

**Comment by pjagielski** [comment]
Ok, after clojurescript upgrade, the only needed script is simple shim which fixes `Function.prototype.bind`.

**Comment by Deraen** [comment]
Okay now diff is looking better.

Could you still squash the commits into one so that the commit with +20000 lines wont get to the index?
`git rebase -i HEAD~2` and selecting squash for the second commit should do.

**Comment by pjagielski** [comment]
squashed

**Pull request merged**
